### ISSUE TITLE
zenstruck redirect

### ISSUE THREAD

**Issue by kbond** [connectjames/spill-kits-direct#1]
Hey,

I just tried this app locally and the redirects work as expected...

`bin/console debug:event`

```
"kernel.exception" event
------------------------

 ------- ---------------------------------------------------------------------------------------- ---------- 
  Order   Callable                                                                                 Priority  
 ------- ---------------------------------------------------------------------------------------- ---------- 
  #1      Zenstruck\RedirectBundle\EventListener\RedirectOnNotFoundListener::onKernelException()   10        
  #2      Zenstruck\RedirectBundle\EventListener\CreateNotFoundListener::onKernelException()       0         
  #3      Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelException()         0         
  #4      Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onException()        0         
  #5      Symfony\Component\HttpKernel\EventListener\ExceptionListener::onKernelException()        -128      
 ------- ---------------------------------------------------------------------------------------- ----------
```

I tried adding a redirect to the database and it redirected as expected. It is also tracking 404 errors.

My steps were as follows:

1. git clone
2. composer install
3. I had to make the twig global params just strings (`sagepay_key` etc) so the app could bootstrap
4. create db
5. create schema
6. run webserver `bin/console server:run`
7. goto `127.0.0.1:8000/not-a-real-uri`
8. check the database - a not found was added for `/not-a-real-uri`
9. manually add a redirect in the db for `/not-a-real-uri` to redirect to `/`
10. goto `127.0.0.1:8000/not-a-real-uri` and was redirected to `/`
11. check the database - the count in the redirect table was increased and timestamp updated

**Comment by connectjames** [comment]
Thanks a lot. All tried and working!
